targetFps: 60
title: "Demo Game"
multiplayer: ${MULTIPLAYER:false}
server: ${SERVER:true}
serverHost: ${SERVER_HOST:localhost}
serverPort: ${SERVER_PORT:8080}
window:
    width: 1280
    height: 900
    resizable: true
    vsync: false
    fullscreen: false
    undecorated: false
    hidden: false
    minimized: false
    maximized: false
    unfocused: false
    topmost: false
    alwaysRun: false
    transparent: false
    highDPI: false
    mousePassthrough: false
    borderlessWindowed: false